### ISSUE TITLE
Allow user to delete the currently pasted ABI 

### ISSUE THREAD

**Issue by jschiarizzi** [blockchainbuddha/one-click-DApps#13]
Currently, if you highlight and delete the ABI in the main paste window, the app will replace it with the default ABI.  I think this is because the form fill if set with a default value instead of a placeholder.

Completion requirement: 
Should allow user to remove the text in the 'paste abi' section without the server filling the text box again.

**Comment by blockchainbuddha** [comment]
Done in commit:352e0c3
