### ISSUE TITLE
json parse error breaks everything

### ISSUE THREAD

**Issue by jschiarizzi** [blockchainbuddha/one-click-DApps#15]
pasting not perfect ABI crashes server.

Desired outcome: pasting not perfect ABI with show an error message popup element that is friendly and links to a knowledge article about what an ABI is

**Comment by jschiarizzi** [comment]
`var forms = []; // Each Method gets a form
  233 | if (this.state.abi) {
  234 |   // check that abi is ready
> 235 |   const abiObject = JSON.parse(this.state.abi);
  236 |   abiObject.forEach((method, i) => {
  237 |     // Iterate only Methods, not Views. NOTE Doesn't get the fallback
  238 |     if (method.stateMutability !== "view" && method.type === "function") {`

**Comment by jschiarizzi** [comment]
check line 235. I think this should have a throw or something

**Comment by blockchainbuddha** [comment]
Fixed in commit:352e0c3 with thanks to @anubhavsa
