### ISSUE TITLE
Given ABI UI, generate new sub-page with ABI UI using node and direct user there

### ISSUE THREAD

**Issue by jschiarizzi** [blockchainbuddha/one-click-DApps#5]
Something like

`//When a user submits a form, create a new page
app.post('/submit', urlencodedParser, function(req, res){   
    var nom = req.body.nom;
    /* save nom to database */
    res.redirect('http://myDomain/' + nom);
});

app.get('/:nom', function(req, res){
    /* if nom exists in database -> return ejs template with vars */
    /* else return 404 */
});`

**Comment by blockchainbuddha** [comment]
Planning on using this https://stackoverflow.com/questions/1201258/how-to-get-a-subdomain-using-window-location

**Comment by anubhavsa** [comment]
I'll try this.
